Last login: Mon Dec 18 00:17:25 on ttys000
localhost:new-jekyll applewang$ cd blog
-bash: cd: blog: No such file or directory
localhost:new-jekyll applewang$ ls
Gemfile		_config.yml	_site		index.md
Gemfile.lock	_posts		about.md
localhost:new-jekyll applewang$ pwd
/Users/applewang/blog/new-jekyll
localhost:new-jekyll applewang$ bundle update github-pages
Could not find gem 'github-pages'.
localhost:new-jekyll applewang$ bundle update
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Warning: Your Ruby version is compiled against a copy of OpenSSL that is very
old. Starting in January 2018, RubyGems.org will refuse connection requests from
these very old versions of OpenSSL. If you will need to continue installing gems
after January 2018, please follow this guide to upgrade:
http://ruby.to/tls-outdated.
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
RubyGems 2.0.14.1 is not threadsafe, so your gems will be installed one at a time. Upgrade to RubyGems 2.1.0 or higher to enable parallel gem installation.
Using public_suffix 2.0.5
Using addressable 2.5.2
Using bundler 1.16.0
Using colorator 1.1.0
Using ffi 1.9.18
Using forwardable-extended 2.6.0
Using rb-fsevent 0.10.2
Using rb-inotify 0.9.10
Using sass-listen 4.0.0
Using sass 3.5.4
Fetching jekyll-sass-converter 1.5.1 (was 1.5.0)


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password: 


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password: 
Installing jekyll-sass-converter 1.5.1 (was 1.5.0)
Fetching listen 3.0.8 (was 3.0.6)
Installing listen 3.0.8 (was 3.0.6)
Using jekyll-watch 1.5.0
Fetching kramdown 1.16.2 (was 1.13.2)
Installing kramdown 1.16.2 (was 1.13.2)
Using liquid 3.0.6
Using mercenary 0.3.6
Using pathutil 0.16.1
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using jekyll 3.4.5
Using jekyll-feed 0.9.2
Using minima 2.1.1
Bundle updated!
localhost:new-jekyll applewang$ ls
Gemfile		_config.yml	_site		index.md
Gemfile.lock	_posts		about.md
localhost:new-jekyll applewang$ vi _config.yml 
localhost:new-jekyll applewang$ bundle update
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Warning: Your Ruby version is compiled against a copy of OpenSSL that is very
old. Starting in January 2018, RubyGems.org will refuse connection requests from
these very old versions of OpenSSL. If you will need to continue installing gems
after January 2018, please follow this guide to upgrade:
http://ruby.to/tls-outdated.
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
RubyGems 2.0.14.1 is not threadsafe, so your gems will be installed one at a time. Upgrade to RubyGems 2.1.0 or higher to enable parallel gem installation.
Using public_suffix 2.0.5
Using addressable 2.5.2
Using bundler 1.16.0
Using colorator 1.1.0
Using ffi 1.9.18
Using forwardable-extended 2.6.0
Using rb-fsevent 0.10.2
Using rb-inotify 0.9.10
Using sass-listen 4.0.0
Using sass 3.5.4
Using jekyll-sass-converter 1.5.1
Using listen 3.0.8
Using jekyll-watch 1.5.0
Using kramdown 1.16.2
Using liquid 3.0.6
Using mercenary 0.3.6
Using pathutil 0.16.1
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using jekyll 3.4.5
Using jekyll-feed 0.9.2
Using minima 2.1.1
Bundle updated!
localhost:new-jekyll applewang$ ll
-bash: ll: command not found
localhost:new-jekyll applewang$ ls
Gemfile		_config.yml	_site		index.md
Gemfile.lock	_posts		about.md
localhost:new-jekyll applewang$ vi _config.yml 
localhost:new-jekyll applewang$ cd ..
localhost:blog applewang$ ls
Gemfile		Gemfile.lock	new-jekyll
localhost:blog applewang$ cd ..
localhost:~ applewang$ ls
Applications		Music			VirtualBox VMs
Desktop			Pictures		_config.yml
Documents		Public			blog
Downloads		README.md		new-jekyll
Library			README的副本.md
Movies			Unity2017.1.1f1
localhost:~ applewang$ vi README.md
localhost:~ applewang$ git pull
Already up-to-date.
localhost:~ applewang$ vi README.md
localhost:~ applewang$ git add README.md
localhost:~ applewang$ git commit -m "attempt add timestamp commit"
[master 32c70a0] attempt add timestamp commit
 1 file changed, 1 insertion(+), 1 deletion(-)
localhost:~ applewang$ git push -u origin master
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 317 bytes | 317.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/susuecho/blog.git
   85bc357..32c70a0  master -> master
Branch master set up to track remote branch master from origin.
localhost:~ applewang$ ll
-bash: ll: command not found
localhost:~ applewang$ ls
Applications		Music			VirtualBox VMs
Desktop			Pictures		_config.yml
Documents		Public			blog
Downloads		README.md		new-jekyll
Library			README的副本.md
Movies			Unity2017.1.1f1
localhost:~ applewang$ cd blog
localhost:blog applewang$ ls
Gemfile		Gemfile.lock	new-jekyll
localhost:blog applewang$ cd new-jekyll/
localhost:new-jekyll applewang$ ls
Gemfile		_config.yml	_site		index.md
Gemfile.lock	_posts		about.md
localhost:new-jekyll applewang$ vi _confi
localhost:new-jekyll applewang$ vi _config.yml 

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Weekly Track
email: secrete@mail.com
description: > # this means to ignore newlines until "baseurl:"
  Awsome.
baseurl: /blog
url: https://susuecho.github.io/blog/
twitter_username: no
github_username:  susuecho

# Build settings
markdown: kramdown
theme: jackman
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
